/*
 * This source file was generated by the Gradle 'init' task
 */
//main package
package src;
//imports
import javafx.application.Application;
import javafx.stage.*;
import javafx.scene.*;
import javafx.graphics.*;


public class App extends Application {
    @Override
    public void start(Stage primaryStage) {
        System.out.println(getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
